apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.19.3/cert-manager.yaml

patches:
  - path: overlays/cert-manager-namespace.yaml
  - path: overlays/patch-priority-class.yaml
    target:
      kind: Deployment
